# Generated by Django 5.1.15 on 2026-08-10 06:12

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('hold_duration_minutes', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('total_capacity', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField(default=0)),
                ('held', models.PositiveIntegerField(default=0)),
                ('price_cents', models.PositiveIntegerField(help_text='Price in integer cents (e.g., 1000 = $10.00)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('sold_out', 'Sold Out')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'ordering': ['price_cents'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sold__gte', 0)), name='chk_sold_non_negative'), models.CheckConstraint(condition=models.Q(('held__gte', 0)), name='chk_held_non_negative'), models.CheckConstraint(condition=models.Q(('sold__lte', django.db.models.expressions.CombinedExpression(models.F('total_capacity'), '-', models.F('held')))), name='chk_no_oversell'), models.CheckConstraint(condition=models.Q(('price_cents__gte', 0)), name='chk_price_positive')],
            },
        ),
    ]
