# Generated by Django 5.1.15 on 2026-08-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='service_fee_cents',
            field=models.PositiveIntegerField(default=0, help_text='Flat per-ticket service fee, in integer cents'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='tax_cents',
            field=models.PositiveIntegerField(default=0, help_text='Flat per-ticket tax, in integer cents'),
        ),
    ]
