# Generated by Django 5.1.15 on 2026-08-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_tickettype_service_fee_cents_tickettype_tax_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sales_paused',
            field=models.BooleanField(default=False, help_text='Ops kill switch: blocks new reservations and pending purchase confirmations for this event.'),
        ),
    ]
