# Generated by Django 5.1.15 on 2026-08-10 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=255)),
                ('changes', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, help_text='Answers WHY the change occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='idx_audit_entity')],
            },
        ),
    ]
