# Generated by Django 5.1.15 on 2026-08-10 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
                ('exception_message', models.TextField()),
                ('retry_count', models.IntegerField(default=0)),
                ('resolution', models.CharField(blank=True, choices=[('retried', 'Retried'), ('refunded', 'Refunded'), ('manual', 'Manual')], max_length=20, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('resolved_at__isnull', True)), fields=['-created_at'], name='idx_failed_task_unresolved')],
            },
        ),
    ]
