# Generated by Django 5.1.15 on 2026-08-10 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_ticket_order_idx_order_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='processed', max_length=20)),
                ('initiated_by', models.CharField(max_length=255)),
                ('payment_refund_id', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('ticket', models.ForeignKey(blank=True, help_text='Nullable - links to single ticket for partial refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='chk_refund_positive')],
            },
        ),
    ]
